### PR TITLE
Cygwin support

### PR DESCRIPTION
**Pull request by vmiheer**

### CODE REVIEW

**Comment by vmiheer** [comment]
@mattfidler, will you please review and merge?
This package is used in [org-pomodoro](https://github.com/lolownia/org-pomodoro).
Thank you,
[+miheer](http://web.cse.ohio-state.edu/~vaidya.56)

**Comment by mattfidler** [comment]
I dont think I havr write access to this repository.

**Comment by vmiheer** [comment]
@syohex, will you please review and merge?
Thank you,
+miheer

**Comment by syohex** [comment]
Sorry for very belated reply.

**Pull request merged**
